version: "3"

services:
    morse-database:
        image: mcr.microsoft.com/mssql/server:2017-latest
        expose:
            - "1433"
        volumes:  
            - mssqlsystem:/var/opt/mssql/ 
            - mssqluser:/var/opt/sqlserver 
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "Password1!"
        labels:
            kompose.service.type: nodeport
    morse-backend:
        image: ghcr.io/moritzeichhorn/morse-backend:latest
        ports:
            - "9190:80"
        links:
            - morse-database
        depends_on:
            - morse-database
        labels:
            kompose.service.type: nodeport
    morse-frontend:
        image: ghcr.io/moritzeichhorn/morse-frontend:latest
        ports:
            - "9090:80"
        labels:
            kompose.service.type: nodeport
volumes:
  mssqlsystem: 
  mssqluser:          
